### ISSUE TITLE
.

### ISSUE THREAD

**Issue by jokerart06** [MrPictYT-art/KMrite#1]

**Comment by MrPictYT-art** [comment]
there is no mistake about them, it works non-root with virtual space. (Tested)
For Root, I don't really know but I assume that it won't work because it needs to have permission superuser for writing into other process memory

**Comment by jokerart06** [comment]
is this external app? or need to combine into apk and run it in virtual?

**Comment by MrPictYT-art** [comment]
external app

**Comment by jokerart06** [comment]
i try this in my rooted device and installed the parallel space but it force close the app inside parallel. is something wrong?

**Comment by MrPictYT-art** [comment]
try get the logcat error and send it

**Comment by jokerart06** [comment]
okay bro. can you also provide video how to make this in nonroot? thank you

**Comment by MrPictYT-art** [comment]
BryanGIG#6254
